version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Optional overrides or runtime-only vars
      DJANGO_SETTINGS_MODULE: friday.settings
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - Friday-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  Friday-data:
  static_volume:
  media_volume: