# Generated by Django 4.2.11 on 2025-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='daily_report',
            field=models.TextField(blank=True, help_text='Employees can fill this out when clocking out.', null=True, verbose_name='Daily Report'),
        ),
    ]
